config/routes.rb
Exam1::Application.routes.draw do
  namespace :admin do
    resources :categories
  end
  resources :users
  resources :sessions
  resources :products
  resources :articles
  root :to => 'home#index'
  get "sign_up" => "users#new", :as => "sign_up"
  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  match ':controller(/:action(/:id(.:format)))'
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  belongs_to :user

  validates :name, :presence => true, :length => {:minimum => 1, :maximum => 150}, :uniqueness => true
  validates :description, :presence => true, :length => {:minimum => 1, :maximum => 2000}
  validates :weight, :presence => true
  validates :price, :presence => true
  validates :category_id, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  has_many :products
  has_many :articles
  before_save :encrypt_password
  validates :password, :presence => {:on => :create},
                       :confirmation => true
  validates :email, :presence => true, :uniqueness => true
  def encrypt_password
    if password.present?
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def is_admin?
    self.email == "admin@admin.com"
  end
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ApplicationController
  protect_from_forgery
  
  def require_admin_login
    if current_user.nil? || !current_user.is_admin?
      flash[:notice] = "Only admin permited"
      redirect_to root_url
    else
      return current_user
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_filter :require_admin_login
  def index
    @categories = Category.all
  end
  
  def new
    @category = Category.new
    @parent_category = Category.where(["parent_id IS NULL"]).map{|x|[x.name, x.id]}
  end

  def create

    @category = Category.new(params[:category])
    if @category.save
      flash[:notice] = "Category Successully created"
      redirect_to admin_categories_path
    else
      flash.now[:error] = "Category failed to create"
      render 'new'
    end
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user


  private
  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

  def require_login
    if current_user.nil?
      flash[:notice] = "You must Login first"
      redirect_to log_in_path
    else
      current_user
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end
  
  def new
    @article = Article.new
  end
  
  def create
    @article = Article.new(params[:article])
    if @article.save
      flash[:notice] = "Article successfully saved"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def show
    @article = Article.find_by_id(params[:id])
  end
 
  def edit
  end

  def update
  end

  def destroy
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @products = Product.limit(6)
    @articles = Article.limit(3)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :require_login, :only => [:new, :edit, :destroy]

  def index
    @categories = (Category.all-Category.where(["parent_id IS NULL"])).map{|x|[x.name, x.id]}
    @products = Product.all#limit(5)

  end

  def new
    @product = Product.new
    @categories = (Category.all-Category.where(["parent_id IS NULL"]))
  end

  def create
    @product = Product.new(params[:product])
    if @product.save
      redirect_to products_path, :notice => "Product successfully listed"
    else
          @categories = (Category.all-Category.where(["parent_id IS NULL"]))
      render 'new'
    end
  end

  def show
    @product = Product.find_by_id(params[:id])
    @category = @product.category.name
  end

  def edit
    @product = Product.find_by_id(params[:id])
    @categories = (Category.all-Category.where(["parent_id IS NULL"]))
  end

  def update
    @product = Product.find_by_id(params[:id])
    if @product.update_attributes(params[:product])
      redirect_to products_path, :notice => "Product successfully updated"
    else
      @categories = (Category.all-Category.where(["parent_id IS NULL"]))
      render 'edit'
    end
  end

  def destroy
    Product.destroy(params[:id])
    redirect_to products_path, :notice => "Product Successfully Deleted"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to user_path(user.id), :notice => "Logged In!!"
    else
      flash.now.alert = "Invalid email or password"
      render "new"
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged Out!!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if verify_recaptcha
      if @user.save
        UserMailer.registration_confirmation(@user).deliver
        redirect_to new_user_path, :notice => "Signed Up!!"
      else
        render :new
      end
    else
      flash.now[:error] = "There was an error with recaptcha code below. Please re enter the code and submit click submit."
      render 'new'
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to user_path, :notice => "User successfully updated"
    else
      flash[:notice] = "User was failed to update"
      render 'edit'
    end
  end
  
  def show
    @user = User.find_by_id(params[:id])
  end
  
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/categories/index.html.erb
<p class=header>Listing Product</p>
<%= link_to "New Category", new_admin_category_path %>

<table>
    <tr class=category_index_table_title>
      <td>Name</td>
      <td>Parent Category</td>
      <td></td>
    </tr>
  <% @categories.each do |category| %>
    <tr>
      <td><%= category.name %></td>
      <td><%= category.parent_category %></td>
    </tr>
  <% end %>
</table>

app/views/admin/categories/new.html.erb
<div class=new_category>
<p>New Category</p>
</div>
<%= form_for @category, :url => admin_categories_path do |category| %>
  <table>
    <tr>
      <td><%= category.label :name %></td>
      <td>: <%= category.text_field :name %></td>
    </tr>
    <tr>
      <td><%= category.label :parent_id, "Parent Category" %></td>
      <td>: <%= category.select :parent_id, @parent_category, { :include_blank => true } %></td>
    </tr>
  </table>
      <%= category.submit %>
<% end %>
  

app/views/articles/index.html.erb
<p class=header>Listing Article</p>
<div><%= flash[:notice] %></div>
<% @articles.each do |article| %>
  <div class=article>
    <p><%= truncate(article.body, :length =>20, :omission => '...') %></p>
    <br />
    <%= link_to "See Details", article_path(article.id) %>
  </div>
<% end %>

app/views/articles/new.html.erb
<p class=header>New Article</p>
<%= form_for @article do |article|%>
  <% if @article.errors.any? %>
    <div class=error_messages>
      <h2>Invalid In Creating Article</h2>
      <ul>
        <% for message in @article.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table>
    <tr>
      <td><%= article.label :title %></td>
      <td><%= article.text_field :title %></td>
    </tr>
    <tr>
      <td><%= article.label :body %></td>
      <td><%= article.text_area :body, :rows => 4 %></td>
    </tr>
  </table>
  <%= article.hidden_field :user_id, :value => current_user.id %>
  <%= article.submit "List Article" %>
<% end %>

app/views/home/index.html.erb
<p class=header>Listing Products</p>
<div><%= flash[:notice] %></div>
<% @products.each do |product| %>
<div class=product>
  <table>
    <tr>
      <td>Name</td>
      <td>: <%= product.name %></td>
    </tr>
    <tr>
      <td>Price</td>
      <td>: <%= product.price %></td>
    </tr>
    <tr>
      <td colspan=2>
        <%= link_to "See More", product_path(product.id) %>
        <% if !current_user.nil? %>
          <% if current_user.id == product.user_id || current_user.is_admin?  %>
            <%= link_to "Edit", edit_product_path(product.id) %>
            <%= link_to "Delete", product_path(product.id), :confirm => "Are you sure want to delete this product?", :method => "delete" %>
          <% end %>
        <% end %>
      </td>
    </tr>
  </table>
</div>
<% end %>
<p class=header>Listing Article</p>
<div><%= flash[:notice] %></div>
<% @articles.each do |article| %>
  <div class=article>
    <p><%= truncate(article.body, :length =>20, :omission => '...') %></p>
    <br />
    <%= link_to "See Details", article_path(article.id) %>
  </div>
<% end %>

app/views/layouts/_after_login.html.erb
<div class=after_login>
  <ul>
    <li><%= link_to "Edit Profile", edit_user_path(current_user.id) %></li>
    <li><%= link_to "Sell a Product", new_product_path %></li>
    <li><%= link_to "Share an Article", new_article_path %></li>
    <li><%= link_to "Logout", log_out_path %></li>
  </ul>
</div>
<% if current_user %>
  <div class=after_login>
    <p>List Category</p>
    <%= raw(list_categories) %>
  </div>
<% end %>

app/views/layouts/_login.html.erb
<h2>Log In</h2>
<%= form_tag sessions_path do %>
  <p>
    <%= label_tag :email %><br />
    <%= text_field_tag :email, params[:email] %>
  </p>
  <p>
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </p>
  <p class="button"><%= submit_tag "Login" %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Exam1</title>
  <%= stylesheet_link_tag    "application","style" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class=container>
    <div id=header>
      <h1>Welcome to my store</h1>
      <ul>
        <% if current_user.nil? %>
          <li><%= link_to 'Sign Up', new_user_path %>
        <% else %>
          <li><%= link_to 'Home', root_url %></li>
        <% end %>
        <li><%= link_to 'Products', products_path %></li>
        <li><%= link_to 'Articles', articles_path %></li>
        <% unless current_user.nil? %>
          <% if current_user.is_admin? %>
            <li><%= link_to 'Category', admin_categories_path %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
    <br class=clear />
    <div id=menu_login>
      <% unless current_user %>
        <%= render :partial => "/layouts/login" %>
      <% else %>
        <%= render :partial => "/layouts/after_login" %>
      <% end %>
    </div>
    <div id=content><%= yield %>
    </div>
  </div>
</body>
</html>

app/views/products/edit.html.erb
<p class=header>New Product</p>

<%= form_for @product do |product| %>
  <% if @product.errors.any? %> 
    <div class="error_messages"> 
      <h2>Form is invalid</h2> 
      <ul> 
        <% for message in @product.errors.full_messages %> 
          <li><%= message %></li> 
        <% end %> 
      </ul> 
    </div> 
  <% end %> 
<table>
  <tr>
    <td><%= product.label :name %></td>
    <td><%= product.text_field :name %></td>
  </tr>
  <tr>
    <td><%= product.label :description %></td>
    <td><%= product.text_area :description, :rows => 4 %></td>
  </tr>
  <tr>
    <td><%= product.label :price %></td>
    <td><%= product.text_field :price, :size => 5, :maxlength => 10 %></td>
  </tr>
  <tr>
    <td><%= product.label :weight %></td>
    <td><%= product.text_field :weight, :size => 5, :maxlength => 10 %></td>
  </tr>
  <tr>
    <td><%= product.label :category_id, "Category" %></td>
    <td><%= product.select :category_id , @categories.map{|x|[x.name,x.id]} %></td>
  </tr>
</table>
<%= product.hidden_field :user_id, :value => current_user.id  %>
<%= product.submit "Update Product" %>
<% end %>

app/views/products/index.html.erb
<p class=header>Listing Products</p>
<div><%= flash[:notice] %></div>
<% @products.each do |product| %>
<div class=product>
  <table>
    <tr>
      <td>Name</td>
      <td>: <%= product.name %></td>
    </tr>
    <tr>
      <td>Price</td>
      <td>: <%= product.price %></td>
    </tr>
    <tr>
      <td colspan=2>
        <%= link_to "See More", product_path(product.id) %>
        <% if !current_user.nil? %>
          <% if current_user.id == product.user_id || current_user.is_admin?  %>
            <%= link_to "Edit", edit_product_path(product.id) %>
            <%= link_to "Delete", product_path(product.id), :confirm => "Are you sure want to delete this product?", :method => "delete" %>
          <% end %>
        <% end %>
      </td>
    </tr>
  </table>
</div>
<% end %>

app/views/products/show.html.erb
<p class=header>Product Details</p>
<table>
  <tr>
    <td>Name</td>
    <td>: <%= @product.name %></td>
  </tr>
  <tr>
    <td>Description</td>
    <td>: <%= @product.description %></td>
  </tr>
  <tr>
    <td>Price</td>
    <td>: <%= @product.price %></td>
  </tr>
  <tr>
    <td>Weight</td>
    <td>: <%= @product.weight %></td>
  </tr>
  <tr>
    <td>Category</td>
    <td>: <%= @category %></td>
  </tr>
  <tr>
    <td>Published By</td>
    <td>: <%= @product.user.name %></td>
  </tr>
</table>
<%= link_to 'Back', products_path %>

app/views/users/edit.html.erb
<h2>Edit Pofile</h2>
<table>
<%= form_for @user, :url => user_path do |user| %>
  <tr>
    <td><%= user.label :name %></td>
    <td><%= user.text_field :name %></td>
  </tr>
  <tr>
    <td><%= user.label :address %></td>
    <td><%= user.text_area :address, :rows => 4 %></td>
  </tr>
  <tr>
    <td><%= user.label :phone_number %></td>
    <td><%= user.text_field :phone_number %></td>
  </tr>
  <tr>
    <td><%= user.label :birthday %></td>
    <td><%= user.date_select(:birthday, :start_year => 1940) %></td>
  </tr>
  <tr>
    <td><%= user.label (:gender) %></td>
    <td><%= user.radio_button(:gender, 0, :checked => (:gender == false)? true:false) %>
        <%= label_tag ("Female") %>
        <%= user.radio_button(:gender, 1, :checked => (:gender == true)? true:false) %>
        <%= label_tag ("Male") %>
    </td>
  </tr>
  <tr>
    <td><%= user.label :facebook %></td>
    <td><%= user.text_field :facebook %></td>
  </tr>
  <tr>
    <td><%= user.label :blog %></td>
    <td><%= user.text_field :blog %></td>
  </tr>
  <tr>
    <td><%= user.submit %></td>
  </tr>

<% end %>
</table>

app/views/users/new.html.erb
<h2> Sign Up </h2>
<%= flash[:error] %>
<%= flash[:notice] %>
<%= form_for @user do |user| %>
  <%if @user.errors.any? %>
    <div class=error_messages>
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <%  end %>
  <p>
    <%= user.label :email %><br />
    <%= user.text_field :email %>
  </p>
  <p>
    <%= user.label :password %><br />
    <%= user.password_field :password %>
  </p>
  <p>
    <%= user.label :password_confirmation %><br />
    <%= user.password_field :password_confirmation%>
  </p>
  <p><%= recaptcha_tags %></p>
  <p class="button"><%= user.submit %></p>
<% end %>

app/views/users/show.html.erb
<h2>User Profile</h2>
<table class=show_profile>
  <tr>
    <td>Email </td>
    <td><%= @user.email %></td>
  </tr>
  <tr>
    <td>Name</td>
    <td><%= @user.name %></td>
  </tr>
  <tr>
    <td>Address</td>
    <td><%= @user.address %></td>
  </tr>
  <tr>
    <td>Birthday</td>
    <td><%= @user.birthday %></td>
  </tr>
  <tr>
    <td>Gender</td>
    <td>
      <% if @user.gender == false %>
        Female
      <% else %>
        Male
      <% end %>
    </td>
  </tr>
  <tr>
    <td>Facebook</td>
    <td><%= @user.facebook %></td>
  </tr>
  <tr>
    <td>Blog</td>
    <td><%= @user.blog %></td>
  </tr>
</table>